dependencies:
  #- <organization/repo>@<version
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.0.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0'
dotenv: .env
networks:
  mainnet-fork-dev: 
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  sepolia: 
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: True